### ISSUE TITLE
Bug: feedback 的 message_id 是 0 

### ISSUE THREAD

**Issue by wling-art** [koishijs/common#16]
使用 onebot 适配器
```
2024-07-28 04:03:32 [W] onebot Error: Error with request get_msg, args: {"message_id":0}, retcode: 200
                            at _Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as getMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:149:20)
                            at async OneBotBot.getMessage (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:925:18)
                            at async adaptMessage (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:336:21)
                            at async adaptSession (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:411:5)
                            at async dispatchSession (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:399:19)
```

**Comment by shigma** [comment]
这是你 onebot 后端的问题，请前往 onebot 后端查询文档。
