### ISSUE TITLE
Bug: forward 有数据库模式下使用指令时显示出现未知错误

### ISSUE THREAD

**Issue by eric2788** [koishijs/common#5]
koishi 版本: v4.15.0

错误日志如下:

```log
2023-10-11 15:41:32 [W] command forward.add #discord:968508697280143391
                        TypeError: Cannot read properties of null (reading 'forward')
                            at getTargets (/koishi/node_modules/koishi-plugin-forward/lib/index.js:144:30)
                            at _Command.<anonymous> (/koishi/node_modules/koishi-plugin-forward/lib/index.js:153:23)
                            at Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1659:27)
                            at argv.next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1671:60)
                            at _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1674:33)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2326:22
                            at async _Session.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2194:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:847:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:847:16)
   ```

**Comment by shigma** [comment]
请问是私聊环境吗？

**Comment by eric2788** [comment]
啊這，原來是要去群聊環境才能設置啊，我還以爲私聊也能設置....
現在用指令沒問題了，但是加了 forward 的頻道之後 我發消息還是沒有自動轉發到目標頻道

**Comment by shigma** [comment]
> 啊這，原來是要去群聊環境才能設置啊，我還以爲私聊也能設置....

之前写的时候没考虑周全，应该加个用法提醒而不是报错。我会改进。

> 現在用指令沒問題了，但是加了 forward 的頻道之後 我發消息還是沒有自動轉發到目標頻道

看下 forward list 输出。

**Comment by eric2788** [comment]
日志輸出貌似沒有反應

**Comment by eric2788** [comment]
forward.list 輸出是有目標頻道的，但是沒有轉發，而且日志輸出也沒有顯示錯誤

**Comment by shigma** [comment]
OK，以后还有问题可以重开。

**Comment by shigma** [comment]
无法转发图片有没有报错信息？

**Comment by eric2788** [comment]
沒有的
我用的red適配器
